### ISSUE TITLE
Enhancement opportunity: To-do-List

### ISSUE THREAD

**Issue by anita00001** [anita00001/To-do-List#6]
## Highlights
✔ Linters check passed
✔Descriptive README.md file
✔ Proper implementation of add, remove, checked, and edit functionality

## Issues:
| Issue | File |
|-----:|-----------|
|     1| index.html |
|     2| style.css |
|     3| localstorage.js |
|     4| completedCheck.js |

<details>
<summary>Issue on index.html: </summary>

- [ ] `<header>` tag would be appropriate tag instead of `<div>`

![image](https://user-images.githubusercontent.com/24216198/223143532-abd9b76a-2b3d-42ad-af6b-259be48bc18c.png)

</details>

<details>
<summary>Issue on style.css:</summary>

- [ ] ``` display: flex;
       align-items: center; ``` is repeated in `body`, `.title`, and `.new-task`

![image](https://user-images.githubusercontent.com/24216198/223146764-dcfa3bad-2f42-4458-b6e2-8ff28cc1a438.png)
![image](https://user-images.githubusercontent.com/24216198/223146390-f41d9a9b-b97d-4d5b-9e57-e29300d2de1f.png)
![image](https://user-images.githubusercontent.com/24216198/223146148-18987ac5-7b0b-43bd-80ef-10fc17cd3b62.png)

These properties can be grouped and written in a single block as,
![image](https://user-images.githubusercontent.com/24216198/223147374-29881ce8-99a3-4902-b163-2788bd14ad9a.png)

- [ ] `border-bottom: 2px solid lightgray;` is repeated three times in `.title`, `.new-task` and 

![image](https://user-images.githubusercontent.com/24216198/223148200-bb631f47-9074-43e6-b3f2-0fabfd03945e.png)
![image](https://user-images.githubusercontent.com/24216198/223148544-f66bff03-49db-47b0-9f77-9d68ccb17236.png)
![image](https://user-images.githubusercontent.com/24216198/223148831-4e7dbf07-1203-479b-8c2d-60bd80b64438.png)

These properties can be grouped and written only once.

- [ ] `cursor: pointer` is used five times in the file specifically in `.title > i`, `#press-enter`, `.task-row > input`, `.task-row i`, and `#clear-button`
       - Don't Repeat Yourself, target `button`, `i` and `input` and grouped them together. 

- [ ] `color: rgba(0, 0, 0, 0.25)` is used three times specifically in `.title > i`, `#press-enter` and `.task-row i`
       - Don't Repeat Yourself, target `button`, `i` and `input` and grouped them together. 

- [ ] `border: none;` is used four times specifically in `input[type=text]`, `#press-enter`, `.task-row .options button` and `#clear-button`
         - Don't Repeat Yourself, target `button`, `p` and `input` and grouped them together. 

- [ ] Targeted class is never created!
![image](https://user-images.githubusercontent.com/24216198/223153084-f9b379ee-b3b5-40f7-a50f-03744456bc01.png)

</details>

<details>
<summary>Issue in localstorage.js:</summary>

- [ ] Functions can be converted into arrow function
![image](https://user-images.githubusercontent.com/24216198/223155914-3f354558-70e2-4956-825f-694d10739444.png)
![image](https://user-images.githubusercontent.com/24216198/223156619-11a9fc6f-0bc9-432d-9e81-23b2abebb031.png)

- [ ] `getFromStorage` function can be written short-hand-code
![image](https://user-images.githubusercontent.com/24216198/223156400-102c91d4-4602-413f-8394-7bc494afbdde.png)

</details>

<details>
<summary>Issue on completedCheck.js:</summary>

- [ ] `toggleCompleted` function can be written short-hand-code
![image](https://user-images.githubusercontent.com/24216198/223157403-043c37a1-a496-4ee2-8165-86f44f8d18ad.png)

</details>

**Comment by anita00001** [comment]
Applied every issues mentioned above
